2 textupload api
exelaration/abstract-memery pull request #21
Opened 2020-02-14 16:10 UTC by sulaip1

I am sending the top text and bottom text fields with a post request which is now sending correctly to the server. Eventually when the db is created, this will be altered so that from the api side the fields will be stored to the db. 

The next step is to combine Jordan's image code with my text code so that they work together. I am going to work on that after I get this merged in.

2020-02-14 16:45 UTC, KatherynRizek submitted a review, later dismissed
Looks good and works locally for me

2020-02-17 14:54 UTC, mchughmk requested changes

2020-02-17 14:54 UTC, mchughmk commented on api/.gitignore
> +gradle/wrapper/gradle-wrapper.jar
These files should not be ignored.  They need to be versioned so everybody works on the same version.

2020-02-17 14:54 UTC, mchughmk commented on api/src/main/java/com/exelaration/abstractmemery/AbstractMemeryApplication.java
> +}
This is being done at the Controller level.  Why are we also doing it at an application level?  I prefer the express intent of doing it at the lower level - either Controller or Action.

2020-02-17 14:54 UTC, mchughmk commented on api/src/main/java/com/exelaration/abstractmemery/controllers/UploadController.java
> +    @GetMapping(value = "/upload", produces = "application/json")
Consider adding the controller's base URL in the `@RestController` attribute instead of at each action.

2020-02-17 15:34 UTC, KatherynRizek approved these changes
Looks good to me

2020-02-17 15:38 UTC, mchughmk approved these changes

2020-02-17 15:39 UTC, merged