Test upload controller
exelaration/abstract-memery pull request #35
Opened 2020-03-19 16:58 UTC by kosmond13

2020-03-23 15:48 UTC, spanjshiri submitted a review, later dismissed
Ran through it locally and it looks good. Don't forget to squash to one commit.

2020-03-24 00:40 UTC, mchughmk requested changes

2020-03-24 00:40 UTC, mchughmk commented on api/src/test/java/com/exelaration/abstractmemery/controllers/UploadControllerTest.java
> +  public void testSaveImageReturns200() throws Exception {
Test names should be specific enough to convey what's being tested and what you expect.  A good rule of thumb is to use the format `FunctionUnderTest_When<SetupConditions>_Expect<Result>`

2020-03-24 00:40 UTC, mchughmk commented on api/src/test/java/com/exelaration/abstractmemery/controllers/UploadControllerTest.java
> +  public void testSaveImageReturns400() throws Exception {
See comment above.

2020-03-24 17:17 UTC, jphilly11 submitted a review, later dismissed

2020-03-25 13:57 UTC, spanjshiri submitted a review, later dismissed

2020-03-25 14:29 UTC, mchughmk approved these changes

2020-03-25 14:33 UTC, spanjshiri approved these changes

2020-03-25 14:34 UTC, jphilly11 approved these changes

2020-03-25 14:35 UTC, merged