Pagination
exelaration/abstract-memery pull request #77
Opened 2020-05-13 17:55 UTC by jphilly11

Adding paging to the meme gallery to get more than just 10 results from the database

2020-05-19 12:44 UTC, mchughmk requested changes

2020-05-19 12:44 UTC, mchughmk commented on ui/src/MemeGallery.tsx
> +      <Button disabled={lastPage} onClick={getNextPage}>Next</Button>
Rather than Previous and Next buttons, let's use [Bootstrap's Pager](https://react-bootstrap.github.io/components/pagination/)

2020-05-20 13:08 UTC, mchughmk requested changes

2020-05-20 13:08 UTC, mchughmk commented on ui/src/MemeGallery.tsx
> +  }
There's a cleaner way to do this using [Array.from](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/from), passing it a `map` function.

2020-05-20 15:21 UTC, mchughmk submitted a review, later dismissed

2020-05-20 15:29 UTC, KatherynRizek approved these changes

2020-05-20 16:36 UTC, mchughmk approved these changes

2020-05-20 16:38 UTC, merged